name: Deploy
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:     
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - uses: actions/checkout@master
      - name: Build image and run container
        run: docker-compose up -d --build
        
      - name: Check container
        run: curl http://localhost:${{ vars.PORT }} 
        
      - name: Push image
        run: docker-compose push
          
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Server container update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_IP }} 
          username: ${{ vars.SERVER_USER }} 
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ vars.IMAGE_NAME }} 
            docker stop ${{ vars.CONTAINER_NAME }} 
            docker rm ${{ vars.CONTAINER_NAME }} 
            docker run -d -p ${{ vars.PORT }}:80 --name ${{ vars.CONTAINER_NAME }}  ${{ vars.IMAGE_NAME }} 
