name: Deploy
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:     
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: $DOCKER_USER
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - uses: actions/checkout@master
      - name: Build image and run container
        run: docker-compose up -d --build
        
      - name: Check container
        run: curl http://localhost:$PORT  
        
      - name: Push image
        run: docker-compose push
          
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Server container update
        uses: appleboy/ssh-action@master
        with:
          host: $SERVER_IP
          username: $SERVER_USER
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull $IMAGE_NAME
            docker stop $CONTAINER_NAME
            docker rm $CONTAINER_NAME
            docker run -d -p $PORT:80 --name $CONTAINER_NAME $IMAGE_NAME
