name: Deploy
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:     
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: actions/checkout@master
      - name: Build and push Compose
        run: |
          docker-compose up -d --build
          docker-compose push     
          
      - name: Check Nginx
        run: curl http://localhost:${{ secrets.PORT }}   
          
      - name: Run server container update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }} 
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMG_NAME }}
            docker stop ${{ secrets.IMG_NAME }}
            docker rm ${{ secrets.IMG_NAME }}
            docker run -d -p ${{ secrets.PORT }}:80 --name ${{ secrets.IMG_NAME }}  ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMG_NAME }}
