name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
#   check: 
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
      
#       - name: Can Build
#         run: docker compose up -d --build

#       - name: Built
#         run: curl http://localhost:9090
          
  build:
#     needs: [check]
    runs-on: ubuntu-latest
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: actions/checkout@master
      - name: Build and push compose
        run: | 
          docker-compose up -d --build
          docker-compose push
        
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }} 
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker compose pull -f docker-compose.yml
            docker compose up -d -f docker-compose.yml --build
      

