name: Check
on:
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:
jobs:     
  check:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: Build image and run container
        run: docker-compose up -d --build
        
      - name: Check container
        run: curl http://localhost:${{ vars.PORT }} 

